// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akqbsuvbammezjyeospk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrcWJzdXZiYW1tZXpqeWVvc3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDEyNTEsImV4cCI6MjA2OTY3NzI1MX0.BQ4HKT4S1FW-MVXiFx_xVl7bcAYbVMto1UxMFHoQzKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});